### ISSUE TITLE
how can I install the command line version for Mac?

### ISSUE THREAD

**Issue by CCLDArjun** [lukechampine/jsteg#1]

**Comment by lukechampine** [comment]
Go calls Mac "darwin", so you just need to download the `jsteg-darwin-amd64` and/or `slink-darwin-amd64` binaries from the [Releases page](https://github.com/lukechampine/jsteg/releases).

**Comment by CCLDArjun** [comment]
i get this: 
![screen shot 2019-02-17 at 7 25 44 pm](https://user-images.githubusercontent.com/31632587/52926248-db541400-32e9-11e9-9051-131e2a7ce70b.png)

**Comment by lukechampine** [comment]
You need to mark the file as executable and then run it from the command line:
```bash
$ chmod +x /path/to/slink
$ ./path/to/slink --help
```
I'll add a note about this on the Releases page.
